### ISSUE TITLE
Proportion unemployed 16-64 y/o is using "White Alone" table

### ISSUE THREAD

**Issue by hhubbell** [iecastro/deprivation-index#1]
Hi,

I noticed in your code that the calculation for percent unemployed for 16-64 y/o in the labor force is using table `C23002A`, which is the "White Alone" group.  Was there a specific reason for choosing this table instead of `C23001`?

The lines of code, for reference:
https://github.com/iecastro/deprivation-index/blob/204d2f9a08705e90bf9ac1da71ac885f6d55bd39/R/ndi.R#L10
https://github.com/iecastro/deprivation-index/blob/204d2f9a08705e90bf9ac1da71ac885f6d55bd39/R/ndi.R#L32

And the Census ACS table index for 2015:
https://www2.census.gov/programs-surveys/acs/tech_docs/table_shells/2015/
[C23001 Table Shell (Excel Download)](https://www2.census.gov/programs-surveys/acs/tech_docs/table_shells/2015/C23001.xlsx)
[C23002A Table Shell (Excel Download)](https://www2.census.gov/programs-surveys/acs/tech_docs/table_shells/2015/C23002A.xlsx)

Thanks!

**Comment by iecastro** [comment]
Thanks @hhubbell, it should not be the "White Alone" group; I have updated this https://github.com/iecastro/deprivation-index/commit/d27cbdedf6af76bf76430332add4a8a963545da6
